config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get "/packages/:name" => "packages#show", as: :package
  devise_for :users
  get "/users/:username" => "users#show"
  use_doorkeeper

  namespace :api, path: "", :constraints => {:subdomain => "api"}, defaults: {format: 'json'} do
    namespace :v0 do
      get "/packages" => "packages#index"
      get "/packages/:name" => "packages#show"
      post "/packages" => "packages#create"
      delete "/packages/:name" => "packages#destroy"

      post "/packages/:name" => "versions#create"
      delete "/packages/:name/:number" => "versions#destroy"
    end
  end

end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  # Assocations
    belongs_to :package
    belongs_to :user
end

app/models/package.rb
class Package < ActiveRecord::Base
  # Assocations
    has_many :users, through: :ownerships
    has_many :ownerships
    has_many :versions

  # Validations
    validates :name, presence: true
    validates :name, uniqueness: true

  # Virtual Attributes
    def description
      if self.versions.any?
        self.versions.last.description
      else
        "null"
      end
    end

    def latest_version
      if self.versions.any?
        self.versions.last
      end
    end

    def latest_version_number
      if self.versions.any?
        self.versions.last.number
      else
        "null"
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Assocations
    has_many :packages, through: :ownerships
    has_many :ownerships

  # Validations
    validates :username, presence: true
    validates :username, uniqueness: true

  # Caching
    if Rails.env.production?
      after_create :purge_all
      after_save :purge
      after_destroy :purge, :purge_all
    end
end

app/models/version.rb
class Version < ActiveRecord::Base
  # Assocations
    belongs_to :package
  
  # Validations
    validates :license, presence: true
    validates :number, presence: true
end

app/controllers/api/v0/packages_controller.rb
class Api::V0::PackagesController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  before_action :doorkeeper_authorize!
  before_action :set_package, only: [:show, :destroy]
  before_action :set_cache_control_headers, only: [:index, :show]
  respond_to :json

  def index
    @packages = Package.all
    set_surrogate_key_header Package.table_key, @packages.map(&:record_key)
  end

  def show
    if @package
      set_surrogate_key_header @package.record_key
      @versions = @package.versions.all if @package.versions.any?
    else
      render json: { error: "Package could not be found." }, status: 404
    end
  end

  def create
    @package = Package.new(package_params)
    if @package.save

      @ownership = Ownership.create!(package_id: @package.id, user_id: current_api_user.id)
      if @ownership.save
        @package.purge_all
        render :show, status: 201
      else
        render :json => { error: "Package could not be saved." }, status: 422
      end

    else
      render :json => { error: "Package could not be saved." }, status: 422
    end
  end

  def destroy
    @ownerships = Ownership.where(package_id: @package.id).all
    if @package.destroy && @ownerships.destroy_all
      @package.purge_all
      render :json => {}, status: 204
    else
      render :json => { error: "Package could not be deleted." }, status: 422
    end
  end

  private
    def set_package
      @package = Package.find_by(name: params[:name])
    end

    def package_params
      params.require(:package).permit(:name)
    end
end

app/controllers/api/v0/versions_controller.rb
class Api::V0::VersionsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  before_action :doorkeeper_authorize!
  before_action :set_package
  before_action :valid_ownership
  respond_to :json

  def create
    if Version.exists?(package_id: @package.id, number: version_params[:number])
      render :json => { error: "Version could not be saved, a version with this number already exists." }, status: 422
      false
    else
      @version = Version.new(version_params.merge(package_id: @package.id))
      if @version.save
        VersionTweeterJob.enqueue(@version.id)
        @version.package.purge
        render :json => {}, status: 201
      else
        render :json => { error: "Version could not be saved." }, status: 422
      end
    end
  end

  def destroy
    @version = Version.joins(:package).where(packages: {name: params[:name]}).find_by(number: params[:number])
    @version.package.purge
    if @version.destroy
      render :json => {}, status: 204
    else
      render :json => { error: "Version could not be deleted." }, status: 422
    end
  end

  private

    def set_package
      @package = Package.find_by(name: params[:name])
    end

    def valid_ownership
      @package = Package.find_by(name: params[:name])
      if Ownership.where(package_id: @package.id, user_id: current_api_user.id).any?
      else
        render :json => { error: "Not authorized." }, status: 401
      end
    end

    def version_params
      params.require(:version).permit(:description, :license, :number, :package_id, :shasum)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :full_name
    devise_parameter_sanitizer.for(:account_update) << :github_username
    devise_parameter_sanitizer.for(:account_update) << :username
    devise_parameter_sanitizer.for(:account_update) << :website
  end

  def current_api_user
    current_user || User.find(doorkeeper_token.resource_owner_id)
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def show
    @package = Package.find_by(name: params[:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @package_count = Package.all.count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_cache_control_headers, only: [:show]

  def show
    @user = User.find_by(username: params[:username])
    set_surrogate_key_header @user.record_key
    @packages = @user.packages.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        Brick
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li> <%= link_to "Account Settings", edit_user_registration_path %> </li>
          <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Robot</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-success alert-dismissible", role: "alert") %>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<div class="center">
  <h1> Brick is a new and improved package manager for Ruby. </h1>

  <br>

  <div class="row">
    <div class="col-md-4">
      <h3>
        <span class="glyphicon glyphicon-paperclip"></span>
        <%= @package_count %> total packages
      </h3>
    </div>

    <div class="col-md-4">
      <h3>
        <span class="glyphicon glyphicon-download"></span>
        12345 downloads today
      </h3>
    </div>

    <div class="col-md-4">
      <h3>
        <span class="glyphicon glyphicon-signal"></span>
        12345 total downloads
      </h3>
    </div>
  </div>

  <hr>

  <h2> Popular packages: </h2>
  <div class="row">
    <div class="col-md-4">
      <h4>devise</h4>
      <p>Flexible authentication solution for Rails with Warden</p>
      <p>3.5.1 published 1 week ago by josevalim</p>
    </div>
    <div class="col-md-4">
      <h4>devise</h4>
      <p>Flexible authentication solution for Rails with Warden</p>
      <p>3.5.1 published 1 week ago by josevalim</p>
    </div>
    <div class="col-md-4">
      <h4>devise</h4>
      <p>Flexible authentication solution for Rails with Warden</p>
      <p>3.5.1 published 1 week ago by josevalim</p>
    </div>
  </div>

  <hr>

  <h2>Getting started: </h2>
  <div class="row">
    <div class="col-md-4">
      <h4>Installing Brick</h4>
      <p>Coming soon.</p>
    </div>
    <div class="col-md-4">
      <h4>Documentation</h4>
      <p>Coming soon.</p>
    </div>
    <div class="col-md-4">
      <h4>Get a job</h4>
      <p>People are hiring!</p>
    </div>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-md-6">
    <h3 class="center">Sign up for our mailing list to get project updates:</h3>
    <form class="navbar-form navbar-right" action="https://github.us9.list-manage.com/subscribe/post?u=fcd8b7ce315167ae596818804&amp;id=669586050b" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank" novalidate="">
      <div class="form-group">
        <input type="email" placeholder="Email" value="" name="EMAIL" id="mce-EMAIL" class="form-control">
      </div>
      <button type="submit" class="btn btn-success">Subscribe</button>
    </form>
  </div>

  <div class="col-md-6">
    <div class="center">
      <h3>Or follow us on Twitter:</h3>
      <iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" src="http://platform.twitter.com/widgets/follow_button.c2221624a19804fbe9017920859c89ce.en.html#_=1433199402589&amp;dnt=false&amp;id=twitter-widget-0&amp;lang=en&amp;screen_name=brickpm&amp;show_count=false&amp;show_screen_name=true&amp;size=l" class="twitter-follow-button twitter-follow-button" title="Twitter Follow Button" data-twttr-rendered="true" style="position: static; visibility: visible; width: 144px; height: 28px;"></iframe>
      <script id="twitter-wjs" src="http://platform.twitter.com/widgets.js"></script>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="center"> <%= @user.username %> </h1>

<br>

<div class="row">
  <div class="col-md-7">
    <h3> <%= @packages.count %> packages by <%= @user.username %></h3>
    <hr>
    <% if @packages && @packages.any? %>
      <% @packages.each do |package| %>
        <h4> <%= link_to "#{package.name}", package_path(package.name) %> </h4>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-5">
    <p>profile picture</p>

    <h3><b> <%= @user.full_name %> </b></h3>
    <hr>

    <% if @user.website %>
      <h3><b> <%= link_to "#{@user.website}", "http://#{@user.website}" %> </b></h3>
      <hr>
    <% end %>
    <% if @user.github_username %>
      <h3><b> <%= link_to "#{@user.github_username} on GitHub", "https://github.com/#{@user.github_username}" %> </b></h3>
      <hr>
    <% end %>
    <h3><b> <%= link_to "#{@user.username} on brick", "http://brick/users/#{@user.username}" %> </b></h3>
  </div>
</div>